### ISSUE TITLE
[Fix] Print, 리스트, While 화살표 위치 수정, else에 들어갈 때 True 박스가 사라지는 버그 수정, 코드흐름 변수 생성이 다른 for, if와 앞단이 안맞는 문제 수정

### ISSUE THREAD

**Issue by seroak** [Co-due/Front#116]
## 📝 Description
**무엇을?**
-  Print, 리스트, While 화살표 위치 수정, if 내부로 들어갈 때 에러 발생 else로 들어가지는 버그 수정

**왜?**
- 시각화 버그 수정

## ❗️Todo
- [x]  Print, 리스트, While 화살표 위치 수정
- [x] else에 들어갈 때 True 박스가 사라지는 버그 수정
- [x] 코드흐름 변수 생성이 다른 for, if와 앞단이 안맞음

## ETC
기타사항
