### ISSUE TITLE
[Search] react query 적용하기

### ISSUE THREAD

**Issue by seroak** [Co-due/Front#18]
## 📝 Description
**무엇을?**
- react query 적용하기

**왜?**
- 프로젝트에서 react query를 이용해서 백엔드와 통신하기 위해

## ❗️Todo
- [x] 검색을 통해 react query 공부
- [x] 강의로 통해 react query 공부
- [x] 프로젝트에 react query 적용해보면서 공부

## ETC
기타사항
